### ISSUE TITLE
** Error: could not read the directory

### ISSUE THREAD

**Issue by ghost** [INRA-LPGP/RadSex#12]
Hi I'm fairly new to bioinformatics and I've been working on your program and I keep getting the error that the directory could not be read when I try to run process. The strange thing about this error is that an empty coverage table is being made in the directory. Any suggestions?

**Comment by RomainFeron** [comment]
Hi dblum940,
Thank you for posting your issue. This error means the program was not able to open the directory specified with the parameter "-d", which could mean that the directory doesn't exist, that there is a problem with the path, or that there is an issue specific to some systems that I have overlooked.
To help me pinpoint the cause, could you post the command your entered and the exact console output you got, as well as information about your Operating System ?

**Comment by ghost** [comment]
Thanks for the quick response. The OS I'm running is Ubuntu- 16.04. Also Below is a screen shot of the 

![help](https://user-images.githubusercontent.com/41023181/42472917-9cac2014-8388-11e8-8b71-7eeb8865b291.JPG)

**Comment by RomainFeron** [comment]
Thanks for posting the screenshot. The problem comes from the space in "My Passport". The current implementation of directory pathes in RADSex doesn't support spaces.
The quicker fix for now is to rename the drive or move the RADSex directory to another folder with no space in the path. I will look for a way to handle spaces in pathes on my side but it may take a little bit of time.

**Comment by ghost** [comment]
Thank you very much for your help. I had a feeling it had to do with that.

**Comment by RomainFeron** [comment]
Support for spaces in string type parameters (including paths) was added with commit https://github.com/RomainFeron/RadSex/commit/995c5bfccaee58a4948af89a0d6b714a183d1dbf
You can update RADSex with "git pull" in the RADSex directory.

As you said you're beginning with bioinformatics, I'll offer some friendly advice:
- In general, it's good practice on linux to not include spaces in folder and file names (you can use "_" instead). It is also easier to not use uppercase, but this is about personal preference.
- I would advise to separate tools and analyses. In your example, you are running the analyses in the RADSex directory, and it may cause problems when you update the tool with "git pull" for instance. In general, it is better to only use a tool's folder for the tool itself and to create a directory for your analysis.

This issue will be closed now, but feel free to contact me with questions at romain.feron[@]inra.fr , I'll be glad to help !
