### ISSUE TITLE
Paired-end reads?

### ISSUE THREAD

**Issue by Astahlke** [INRA-LPGP/RadSex#14]
Hi again, 

Can RadSex handle paired-end samples explicity? Can I concatenate the pairs together per sample? Would it throw the software if  I left paired-end samples as <sample>.1.fq <sample>.2.fq? 

Thanks!

**Comment by RomainFeron** [comment]
Hey again !
There may be an issue if the insert size is not constant for each RAD cutting site. Basically for RADSex to work you want to have reads coming from exactly the same genomic position. If that's the case then you can indeed concatenate r1 and r2 to only have one input file per sample. Let me know if it worked !
