### ISSUE TITLE
ddRADSeq works?

### ISSUE THREAD

**Issue by HanXiaoEvo** [INRA-LPGP/RadSex#21]
Hi Romain,

I am highly interested in RADSex but a super naive question, is it also suitable for ddRADSeq data? In the paper, you didn't mention if it works for other RAd protocols so I guess it is better to ask. Thank you very much!

Best regards,
Han Xiao

**Comment by RomainFeron** [comment]
Hi Han Xiao,

RADSex works with ddRADSeq as long as the same enzymes are used for all samples :)

Cheers,
Romain

**Comment by HanXiaoEvo** [comment]
Hi  Romain,

Great to know and I will have a try as soon as possible! Super excited!

Cheers,
Han

**Comment by RomainFeron** [comment]
Thank you! Don't hesitate if you have questions while using it :)
