### ISSUE TITLE
RADSEX stuck at 22%

### ISSUE THREAD

**Issue by melodysyue** [INRA-LPGP/RadSex#23]
When I ran RADSEX (distrib, signif and map) on my dataset, all three programs got stuck at 22%. It's been almost three days.

Here are the commands I ran:
radsex distrib --markers-table lwf_markers_table.tsv --popmap lwf_sexmap_N1126.tsv --output-file lwf_distrib_d5.tsv --min-depth 5 --groups M,F
radsex signif --markers-table lwf_markers_table.tsv --output-file lwf_sig_markers_d5.tsv --popmap lwf_sexmap_N1126.tsv --min-depth 5 --groups M,F 
radsex map --markers-file lwf_markers_table.tsv --output-file lwf_map_d5.tsv --popmap lwf_sexmap_N1126.tsv --genome-file ../reference/AWG_v2_GCA902810595.fasta --min-quality 20 --min-frequency 0.1  --min-depth 5 --groups M,F

I also attached the errors files, where you can see the programs got stuck at 22%. 
[radsex_lwf_errors.zip](https://github.com/SexGenomicsToolkit/radsex/files/6378416/radsex_lwf_errors.zip)

I ran the programs on a high-memory node on a cluster. The dataset is generated by Rapture sequencing and consists of 1126 individuals and 309,780,350 markers according to the lwf_markers_table.tsv. 

Is it because the dataset is too big? Any suggests how to fix it?

Thanks,
Yue

**Comment by RomainFeron** [comment]
Hi Yue,

This is definitely a huge dataset, much bigger than any I've tried radsex on, so I would not be surprised in the number of markers is an issue. It's interesting that "radsex process" ran fine though, as it is by far the most memory intensive step.

Did you submit a job to the high-mem node or did you run radsex directly on it? Did you get any error message indicating this is a memory issue?
One thing you could try to do, if your dataset has sufficient coverage per individual (let's say 5-10 at least, ideally more), is to generate the table of marker depths with a minimum depth value of 2 or 3 (by default, it is 1). This would remove a lot of noise from sequencing error and sequences found in only one individual, and should hopefully reduce the number of reads a lot.

Cheers,
Romain

**Comment by melodysyue** [comment]
Thanks for your response, Romain! 

I submitted the slurm jobs to the high-mem node. There were no error messages other than the fact that programs got stuck at 22% and not progressing any more. 

I will try regenerate the marker table with a minimum depth value of 2 and let you know if it fixes the problem. It sound like a good idea!

Yue

**Comment by RomainFeron** [comment]
Hi Yue,

I was wondering because for me, when using slurm, there are specific error messages associated with using too much memory in the ".err" file, so it would be easy to spot. Here I don't see these messages in your logs, so it's likely the issue does not come from memory but from something else (it's also possible your cluster is configured differently but I think it's less likely). 

Let me know if using a min depth of 2 for the markers table fixed this issue, otherwise there is a likely a specific bug in radsex that is triggered by your data, and we can see how to find it.

Cheers,
Romain

**Comment by melodysyue** [comment]
Hi Romain,

Using a min depth of 2 for the markers table fixed the issue! Thanks for your help!

Yue

**Comment by RomainFeron** [comment]
Hi Yue,

My guess is that something went wrong with job submission on the high-mem node and radsex required more memory than was available. I'm glad it worked out in the end! 

Cheers,
Romain
