### ISSUE TITLE
markers table only generates markers in single individual

### ISSUE THREAD

**Issue by jwiggi18** [INRA-LPGP/RadSex#24]
Hello, 
I've attempted to run the radsex pipeline on ddRAD data repeatedly and in every iteration have only a single column with any markers in the markers table. I've used data downloaded from SRA as well as the raw data that I cleaned myself. I've also tried removing the individual with markers and rerunning and I get only a singe column again with markers (different individual). These data run fine in the STACKS denovo pipeline. Any thoughts on what I might be doing wrong here?

**Comment by jwiggi18** [comment]
In case it helps, this is the project I'm working from (only the Crotaphytus collaris indvs)
https://www.ncbi.nlm.nih.gov/sra/SRX3380910[accn]

**Comment by RomainFeron** [comment]
Hi,
I've tried downloading the dataset to check it myself but the barcodes are not easy to find, could you send me the barcodes file you used for demultiplexing?

**Comment by jwiggi18** [comment]
absolutely, 
[Run_ID_adapter.xls](https://github.com/SexGenomicsToolkit/radsex/files/6946768/Run_ID_adapter.xls)

It is my understanding that the barcodes were removed prior to the SRA upload as the individuals are sorted and labeled but I've had fits with these data so certainly could be mistaken.

**Comment by RomainFeron** [comment]
I got confused originally because I didn't realize individual reads had been uploaded separately on NCBI. I managed to download reads for all samples on NCBI and I got the following folder structure:

```
└── samples
    ├── SRR6278191.fastq
    ├── SRR6278192.fastq
    ├── SRR6278193.fastq
    ├── SRR6278194.fastq
    ├── SRR6278195.fastq
    ├── SRR6278196.fastq
    ├── SRR6278197.fastq
    ├── SRR6278198.fastq
    ├── SRR6278199.fastq
    ├── SRR6278200.fastq
    ├── SRR6278201.fastq
    ├── SRR6278202.fastq
    ├── SRR6278205.fastq
    ├── SRR6278206.fastq
    ├── SRR6278207.fastq
    ├── SRR6278208.fastq
    ├── SRR6278212.fastq
    ├── SRR6278213.fastq
    ├── SRR6278215.fastq
    ├── SRR6278216.fastq
    ├── SRR6278217.fastq
    ├── SRR6278218.fastq
    ├── SRR6278219.fastq
    ├── SRR6278220.fastq
    ├── SRR6278225.fastq
    ├── SRR6278241.fastq
    ├── SRR6278242.fastq
    ├── SRR6278243.fastq
    ├── SRR6278244.fastq
    ├── SRR6278245.fastq
    ├── SRR6278246.fastq
    ├── SRR6278261.fastq
    ├── SRR6278263.fastq
    ├── SRR6278264.fastq
    ├── SRR6278269.fastq
    ├── SRR6278270.fastq
    ├── SRR6278271.fastq
    ├── SRR6278272.fastq
    ├── SRR6278273.fastq
    ├── SRR6278274.fastq
    ├── SRR6278275.fastq
    ├── SRR6278276.fastq
    ├── SRR6278277.fastq
    ├── SRR6278278.fastq
    ├── SRR6278279.fastq
    └── SRR6278280.fastq
```

With this, I ran `radsex process -i samples -o markers.tsv -T 4 -d 5` (I used -d 5 just to speed up the process) and I got a marker table that looks normal:

```
#Number of markers : 24891875
id	sequence	SRR6278278	SRR6278202	SRR6278218	SRR6278263	SRR6278194	SRR6278279	SRR6278199	SRR6278246	SRR6278213	SRR6278206	SRR6278277	SRR6278220	SRR6278196	SRR6278205	SRR6278198	SRR6278273	SRR6278216	SRR6278195	SRR6278207	SRR6278217	SRR6278244	SRR6278201	SRR6278261	SRR6278219	SRR6278197	SRR6278241	SRR6278274	SRR6278264	SRR6278275	SRR6278271	SRR6278200	SRR6278242	SRR6278280	SRR6278276	SRR6278245	SRR6278212	SRR6278192	SRR6278272	SRR6278270	SRR6278193	SRR6278243	SRR6278215	SRR6278225	SRR6278208	SRR6278269	SRR6278191
0	AAAACAGTTTTTTGGAGCTTGAAATATGTGAGGAGGGCAGAGCTTGGTGGGAAACACATGGCCCTCCAGATGTTGGTCAGCAGCTCTGTC	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	00	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	6	0	0	0
1	TACTTTCACCAAGTATCTAGACCACTGGTTCTTAAACTGCGGTCTGTGGACCCCCAGGAGTCCTCAATGCCCTCACAGGGGGTCTGCGAA	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	00	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	6	0	0	0
2	CATGGTTCTGCTCCAGTTTTGGAAGACCAATATGCTAAACTCTTTGGAATCATTAGCTATGGAGGATTTTTAGTCTATGGGTGAATGTCA	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	00	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	5	0	0	0

```
Could you tell me if you did something differently from me?

**Comment by jwiggi18** [comment]
Maybe I am misunderstanding what I'm looking for. There is only one column that has numbers other than "0" does that not indicate that markers were only detected in one individual?

**Comment by RomainFeron** [comment]
I understand that it can be a bit confusing but it's expected for the markers table. The reason is that many markers are found in only one individual with low depth (usually a depth of 1, most likely sequencing errors). This happens in most dataset and it's the reason for the parameter --min-depth in downstream analyses. If your dataset has a high enough average marker depth (let's say 20-30) I recommend setting --min-depth to at least 5 in downstream analyses to filter out markers like the ones you see in the table. I hope that makes sense!

**Comment by jwiggi18** [comment]
Thanks!

**Comment by RomainFeron** [comment]
No worries, let me know if you encounter further issues in the future!
