### ISSUE TITLE
WGRS data

### ISSUE THREAD

**Issue by vunguyen1907** [INRA-LPGP/RadSex#29]
Hi. 

I had whole genome resequencing data of 49 fish with a sex ratio is 23:26. I am not sure if the radsex pipeline works with my data or what I can do to make my data as proper input to radsex? 

Thanks
Vu

**Comment by RomainFeron** [comment]
Hi,

What kind of sequencing data is that? RADSex can only process RAD-Sequencing data and doesn't work well with paired-end. If your data is RAD-Sequencing single end, it would be a great dataset to use RADSex on.

Cheers,
Romain

**Comment by vunguyen1907** [comment]
Hi Romain,

Thanks for your prompt response.

Yes, my data is paired-end reads.
I think there was not much difference between radseq and wgrs data with single-end vs paired-end.

My reads were also about 90-100 bases long after QC, not that more than radseq data (~ 80-90 bases). Why radsex will not work well with such data?

Thanks,
Vu

**Comment by RomainFeron** [comment]
Hi Vu,

The big difference between wgs and RAD-Sequencing is the RAD-Sequencing reads are always coming from the same set of positions in the genome (restriction enzyme cutting sites), so they can be grouped into markers and compared between individuals. WGS reads are everywhere in the genome and it's thus not possible to group them into markers with radsex.

With WGS I would instead align reads to the reference assembly, call SNPs, and look for SNPs with a bias between your two groups (or even SNPs with specific patterns following expected sex determination systems, i.e. 0.5 coverage in males and 1 coverage in females for an XX/XY system). 

Let me know if this is clear,
Cheers,
Romain

**Comment by vunguyen1907** [comment]
Hi Romain,

Thanks for your feedback. I shall find out another way to discover my data.

Regards,

Vu
